/**
 * Dumps the live database schema to backend/db/schema.sql.
 *
 * Connects to the DB configured in .env, iterates every table, runs
 * SHOW CREATE TABLE, and writes the concatenated DDL to a single file.
 *
 * Run with:  npm run schema:dump
 *
 * The seeder also calls this at the end so the file stays in sync after
 * every fresh `npm run seed`. For production deploys, apply schema.sql
 * to a fresh database (mysql DB < backend/db/schema.sql) then optionally
 * run the seeder for sample data.
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { sequelize } = require('../src/models');

async function dumpSchema() {
  await sequelize.authenticate();
  const dbName = sequelize.config.database;

  const [tables] = await sequelize.query('SHOW TABLES');
  const tableKey = `Tables_in_${dbName}`;
  const tableNames = tables.map((t) => t[tableKey]).sort();

  if (tableNames.length === 0) {
    throw new Error(
      `No tables found in database "${dbName}". Run \`npm run seed\` first to create the schema.`
    );
  }

  const lines = [
    '-- ERP database schema',
    '-- Auto-generated by `npm run schema:dump`',
    `-- Source database: ${dbName}`,
    `-- Generated: ${new Date().toISOString()}`,
    '-- DO NOT EDIT MANUALLY — your changes will be overwritten on next dump.',
    '--',
    '-- To deploy on a fresh database:',
    '--   mysql -u <user> -p <database> < backend/db/schema.sql',
    '',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
  ];

  for (const name of tableNames) {
    const [[row]] = await sequelize.query(`SHOW CREATE TABLE \`${name}\``);
    lines.push(`-- ----- ${name} -----`);
    lines.push(`DROP TABLE IF EXISTS \`${name}\`;`);
    lines.push(`${row['Create Table']};`);
    lines.push('');
  }

  lines.push('SET FOREIGN_KEY_CHECKS = 1;');
  lines.push('');

  const outPath = path.join(__dirname, '..', 'db', 'schema.sql');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n'));

  return { outPath, tableCount: tableNames.length };
}

if (require.main === module) {
  dumpSchema()
    .then(({ outPath, tableCount }) => {
      const rel = path.relative(process.cwd(), outPath).replace(/\\/g, '/');
      console.log(`Schema dumped to ${rel} (${tableCount} tables)`);
      return sequelize.close();
    })
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Schema dump failed:', err.message);
      process.exit(1);
    });
}

module.exports = dumpSchema;
