-- ERP database schema
-- Auto-generated by `npm run schema:dump`
-- Source database: erp_system
-- Generated: 2026-05-07T06:11:45.987Z
-- DO NOT EDIT MANUALLY — your changes will be overwritten on next dump.
--
-- To deploy on a fresh database:
--   mysql -u <user> -p <database> < backend/db/schema.sql

SET FOREIGN_KEY_CHECKS = 0;

-- ----- accounts -----
DROP TABLE IF EXISTS `accounts`;
CREATE TABLE `accounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `type` enum('ASSET','LIABILITY','INCOME','EXPENSE') NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `balance` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Running balance — updated on each transaction',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `accounts_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- brands -----
DROP TABLE IF EXISTS `brands`;
CREATE TABLE `brands` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `brands_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- categories -----
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `categories_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- companies -----
DROP TABLE IF EXISTS `companies`;
CREATE TABLE `companies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `gst_number` varchar(15) DEFAULT NULL COMMENT 'Indian GST number (15 chars)',
  `pan_number` varchar(10) DEFAULT NULL,
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `pincode` varchar(10) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'India',
  `currency` varchar(3) DEFAULT 'INR',
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `logo_url` varchar(500) DEFAULT NULL,
  `owner_id` int DEFAULT NULL COMMENT 'User who created/owns this company',
  `tenant_id` int DEFAULT NULL COMMENT 'Tenant this company belongs to',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `owner_id` (`owner_id`),
  KEY `tenant_id` (`tenant_id`),
  CONSTRAINT `companies_ibfk_15` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `companies_ibfk_16` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- currencies -----
DROP TABLE IF EXISTS `currencies`;
CREATE TABLE `currencies` (
  `code` varchar(3) NOT NULL COMMENT 'ISO 4217: INR, USD, EUR, GBP',
  `symbol` varchar(5) NOT NULL,
  `name` varchar(50) NOT NULL,
  `decimal_places` int DEFAULT '2',
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- customers -----
DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `address` text,
  `gst_number` varchar(15) DEFAULT NULL,
  `country` varchar(2) DEFAULT 'IN' COMMENT 'ISO 3166-1 alpha-2',
  `state` varchar(50) DEFAULT NULL COMMENT 'State/province for tax determination',
  `tax_id` varchar(30) DEFAULT NULL COMMENT 'Tax ID: GSTIN (India), EIN/SSN (US), VAT (EU)',
  `credit_limit` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '0 = no limit',
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `customers_phone` (`phone`),
  KEY `customers_name` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `customers_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- exchange_rates -----
DROP TABLE IF EXISTS `exchange_rates`;
CREATE TABLE `exchange_rates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `from_currency` varchar(3) NOT NULL,
  `to_currency` varchar(3) NOT NULL,
  `rate` decimal(14,6) NOT NULL COMMENT '1 unit of from_currency = rate units of to_currency',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `exchange_rates_from_currency_to_currency` (`from_currency`,`to_currency`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- inventory -----
DROP TABLE IF EXISTS `inventory`;
CREATE TABLE `inventory` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `product_id` int NOT NULL,
  `warehouse_id` int DEFAULT NULL COMMENT 'Nullable for single-warehouse setups',
  `stock_quantity` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `inventory_product_warehouse_unique` (`product_id`,(coalesce(`warehouse_id`,0))),
  KEY `inventory_product_id` (`product_id`),
  KEY `company_id` (`company_id`),
  KEY `warehouse_id` (`warehouse_id`),
  CONSTRAINT `inventory_ibfk_22` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `inventory_ibfk_23` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `inventory_ibfk_24` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- payments -----
DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `sale_id` int NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `method` enum('CASH','UPI','CARD') NOT NULL,
  `reference` varchar(100) DEFAULT NULL COMMENT 'Transaction ID / UPI ref / cheque no.',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `payments_sale_id` (`sale_id`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `payments_ibfk_15` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `payments_ibfk_16` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- permissions -----
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `module` varchar(50) NOT NULL COMMENT 'ERP module this permission belongs to (e.g. users, company, inventory)',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- products -----
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `sku` varchar(50) NOT NULL,
  `barcode` varchar(100) DEFAULT NULL,
  `hsn_code` varchar(8) DEFAULT NULL COMMENT 'HSN/SAC code for GST classification',
  `category_id` int DEFAULT NULL,
  `brand_id` int DEFAULT NULL,
  `purchase_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `selling_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `tax_rate` decimal(5,2) NOT NULL DEFAULT '18.00' COMMENT 'GST percentage',
  `unit` varchar(20) NOT NULL DEFAULT 'pcs',
  `min_stock_alert` int NOT NULL DEFAULT '10',
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sku` (`sku`),
  UNIQUE KEY `products_sku` (`sku`),
  UNIQUE KEY `sku_2` (`sku`),
  UNIQUE KEY `sku_3` (`sku`),
  UNIQUE KEY `sku_4` (`sku`),
  UNIQUE KEY `sku_5` (`sku`),
  UNIQUE KEY `sku_6` (`sku`),
  UNIQUE KEY `sku_7` (`sku`),
  UNIQUE KEY `sku_8` (`sku`),
  UNIQUE KEY `barcode` (`barcode`),
  UNIQUE KEY `products_barcode` (`barcode`),
  UNIQUE KEY `barcode_2` (`barcode`),
  UNIQUE KEY `barcode_3` (`barcode`),
  UNIQUE KEY `barcode_4` (`barcode`),
  UNIQUE KEY `barcode_5` (`barcode`),
  UNIQUE KEY `barcode_6` (`barcode`),
  UNIQUE KEY `barcode_7` (`barcode`),
  UNIQUE KEY `barcode_8` (`barcode`),
  KEY `products_category_id` (`category_id`),
  KEY `products_brand_id` (`brand_id`),
  KEY `products_status` (`status`),
  KEY `products_hsn_code` (`hsn_code`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `products_ibfk_22` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `products_ibfk_23` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `products_ibfk_24` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- purchase_items -----
DROP TABLE IF EXISTS `purchase_items`;
CREATE TABLE `purchase_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `purchase_id` int NOT NULL,
  `product_id` int NOT NULL,
  `product_name` varchar(255) NOT NULL COMMENT 'Snapshot at time of purchase',
  `product_sku` varchar(50) NOT NULL,
  `quantity` int NOT NULL,
  `unit_price` decimal(12,2) NOT NULL COMMENT 'Purchase price per unit',
  `tax_rate` decimal(5,2) NOT NULL,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total` decimal(12,2) NOT NULL DEFAULT '0.00',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `purchase_items_purchase_id` (`purchase_id`),
  KEY `purchase_items_product_id` (`product_id`),
  CONSTRAINT `purchase_items_ibfk_15` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `purchase_items_ibfk_16` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- purchases -----
DROP TABLE IF EXISTS `purchases`;
CREATE TABLE `purchases` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `purchase_number` varchar(30) NOT NULL,
  `supplier_id` int NOT NULL,
  `total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `final_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `paid_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `payment_status` enum('PAID','PARTIAL','UNPAID') NOT NULL DEFAULT 'UNPAID',
  `notes` text,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `purchase_number` (`purchase_number`),
  UNIQUE KEY `purchases_purchase_number` (`purchase_number`),
  UNIQUE KEY `purchase_number_2` (`purchase_number`),
  UNIQUE KEY `purchase_number_3` (`purchase_number`),
  UNIQUE KEY `purchase_number_4` (`purchase_number`),
  UNIQUE KEY `purchase_number_5` (`purchase_number`),
  UNIQUE KEY `purchase_number_6` (`purchase_number`),
  UNIQUE KEY `purchase_number_7` (`purchase_number`),
  UNIQUE KEY `purchase_number_8` (`purchase_number`),
  KEY `purchases_supplier_id` (`supplier_id`),
  KEY `purchases_payment_status` (`payment_status`),
  KEY `purchases_created_at` (`created_at`),
  KEY `idx_purchases_report` (`created_at`,`total_amount`,`tax_amount`,`final_amount`,`paid_amount`),
  KEY `company_id` (`company_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `purchases_ibfk_22` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `purchases_ibfk_23` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `purchases_ibfk_24` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- quotation_items -----
DROP TABLE IF EXISTS `quotation_items`;
CREATE TABLE `quotation_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `quotation_id` int NOT NULL,
  `product_id` int NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_sku` varchar(50) NOT NULL,
  `quantity` int NOT NULL,
  `unit_price` decimal(12,2) NOT NULL,
  `tax_rate` decimal(5,2) NOT NULL,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total` decimal(12,2) NOT NULL DEFAULT '0.00',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `quotation_items_quotation_id` (`quotation_id`),
  KEY `quotation_items_product_id` (`product_id`),
  CONSTRAINT `quotation_items_ibfk_15` FOREIGN KEY (`quotation_id`) REFERENCES `quotations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `quotation_items_ibfk_16` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- quotations -----
DROP TABLE IF EXISTS `quotations`;
CREATE TABLE `quotations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `quotation_number` varchar(30) NOT NULL,
  `customer_id` int DEFAULT NULL,
  `total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `final_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `status` enum('DRAFT','SENT','ACCEPTED','REJECTED','CONVERTED') NOT NULL DEFAULT 'DRAFT',
  `valid_until` date DEFAULT NULL,
  `notes` text,
  `converted_sale_id` int DEFAULT NULL COMMENT 'Sale ID if converted',
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `quotation_number` (`quotation_number`),
  UNIQUE KEY `quotations_quotation_number` (`quotation_number`),
  UNIQUE KEY `quotation_number_2` (`quotation_number`),
  UNIQUE KEY `quotation_number_3` (`quotation_number`),
  UNIQUE KEY `quotation_number_4` (`quotation_number`),
  UNIQUE KEY `quotation_number_5` (`quotation_number`),
  UNIQUE KEY `quotation_number_6` (`quotation_number`),
  UNIQUE KEY `quotation_number_7` (`quotation_number`),
  UNIQUE KEY `quotation_number_8` (`quotation_number`),
  KEY `quotations_customer_id` (`customer_id`),
  KEY `quotations_status` (`status`),
  KEY `quotations_created_at` (`created_at`),
  KEY `company_id` (`company_id`),
  KEY `converted_sale_id` (`converted_sale_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `quotations_ibfk_29` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `quotations_ibfk_30` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `quotations_ibfk_31` FOREIGN KEY (`converted_sale_id`) REFERENCES `sales` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `quotations_ibfk_32` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- role_permissions -----
DROP TABLE IF EXISTS `role_permissions`;
CREATE TABLE `role_permissions` (
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `role_id` int NOT NULL,
  `permission_id` int NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- roles -----
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- sale_items -----
DROP TABLE IF EXISTS `sale_items`;
CREATE TABLE `sale_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sale_id` int NOT NULL,
  `product_id` int NOT NULL,
  `product_name` varchar(255) NOT NULL COMMENT 'Snapshot — product name at time of sale',
  `product_sku` varchar(50) NOT NULL COMMENT 'Snapshot — SKU at time of sale',
  `quantity` int NOT NULL,
  `unit_price` decimal(12,2) NOT NULL COMMENT 'Locked selling price at time of sale',
  `tax_rate` decimal(5,2) NOT NULL COMMENT 'GST % at time of sale',
  `tax_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '(unit_price * quantity) + tax_amount',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sale_items_sale_id` (`sale_id`),
  KEY `sale_items_product_id` (`product_id`),
  KEY `idx_sale_items_covering` (`sale_id`,`product_id`,`quantity`,`total`),
  CONSTRAINT `sale_items_ibfk_15` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sale_items_ibfk_16` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- sales -----
DROP TABLE IF EXISTS `sales`;
CREATE TABLE `sales` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `invoice_number` varchar(30) NOT NULL,
  `customer_id` int DEFAULT NULL COMMENT 'Null for walk-in customers',
  `quotation_id` int DEFAULT NULL COMMENT 'If converted from a quotation',
  `total_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `tax_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `final_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `paid_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `payment_status` enum('PAID','PARTIAL','UNPAID') NOT NULL DEFAULT 'UNPAID',
  `payment_method` enum('CASH','UPI','CARD','MIXED') DEFAULT NULL,
  `notes` text,
  `irn` varchar(64) DEFAULT NULL COMMENT 'Invoice Reference Number from e-invoice portal',
  `qr_code` text COMMENT 'QR code data string from e-invoice',
  `e_invoice_status` enum('PENDING','GENERATED','FAILED') DEFAULT NULL,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `invoice_number` (`invoice_number`),
  UNIQUE KEY `sales_invoice_number` (`invoice_number`),
  UNIQUE KEY `invoice_number_2` (`invoice_number`),
  UNIQUE KEY `invoice_number_3` (`invoice_number`),
  UNIQUE KEY `invoice_number_4` (`invoice_number`),
  UNIQUE KEY `invoice_number_5` (`invoice_number`),
  UNIQUE KEY `invoice_number_6` (`invoice_number`),
  UNIQUE KEY `invoice_number_7` (`invoice_number`),
  UNIQUE KEY `invoice_number_8` (`invoice_number`),
  KEY `sales_customer_id` (`customer_id`),
  KEY `sales_payment_status` (`payment_status`),
  KEY `sales_created_at` (`created_at`),
  KEY `sales_quotation_id` (`quotation_id`),
  KEY `idx_sales_report` (`created_at`,`total_amount`,`tax_amount`,`discount_amount`,`final_amount`,`paid_amount`),
  KEY `idx_sales_customer` (`customer_id`,`final_amount`,`paid_amount`,`created_at`),
  KEY `company_id` (`company_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `sales_ibfk_22` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `sales_ibfk_23` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `sales_ibfk_24` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- stock_movements -----
DROP TABLE IF EXISTS `stock_movements`;
CREATE TABLE `stock_movements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `product_id` int NOT NULL,
  `warehouse_id` int DEFAULT NULL,
  `type` enum('IN','OUT','ADJUSTMENT') NOT NULL,
  `quantity` int NOT NULL COMMENT 'Positive for IN/ADJUSTMENT-add, negative for OUT/ADJUSTMENT-subtract',
  `reference` varchar(100) NOT NULL DEFAULT 'manual' COMMENT 'e.g. purchase, sale, manual, return',
  `notes` varchar(500) DEFAULT NULL,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `stock_movements_product_id` (`product_id`),
  KEY `stock_movements_type` (`type`),
  KEY `stock_movements_created_at` (`created_at`),
  KEY `company_id` (`company_id`),
  KEY `warehouse_id` (`warehouse_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `stock_movements_ibfk_29` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_ibfk_30` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_ibfk_31` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_ibfk_32` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- supplier_payments -----
DROP TABLE IF EXISTS `supplier_payments`;
CREATE TABLE `supplier_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `purchase_id` int NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `method` enum('CASH','UPI','BANK') NOT NULL,
  `reference` varchar(100) DEFAULT NULL COMMENT 'Cheque no / UTR / transaction ref',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `supplier_payments_purchase_id` (`purchase_id`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `supplier_payments_ibfk_15` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `supplier_payments_ibfk_16` FOREIGN KEY (`purchase_id`) REFERENCES `purchases` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- suppliers -----
DROP TABLE IF EXISTS `suppliers`;
CREATE TABLE `suppliers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `address` text,
  `gst_number` varchar(15) DEFAULT NULL,
  `country` varchar(2) DEFAULT 'IN',
  `state` varchar(50) DEFAULT NULL,
  `tax_id` varchar(30) DEFAULT NULL COMMENT 'Tax ID: GSTIN, EIN, VAT number',
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `suppliers_phone` (`phone`),
  KEY `suppliers_name` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `suppliers_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- tax_rules -----
DROP TABLE IF EXISTS `tax_rules`;
CREATE TABLE `tax_rules` (
  `id` int NOT NULL AUTO_INCREMENT,
  `country` varchar(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2: IN, US, GB, etc.',
  `state` varchar(50) DEFAULT NULL COMMENT 'State/province code. NULL = applies to entire country',
  `tax_type` varchar(30) NOT NULL COMMENT 'e.g. CGST, SGST, IGST, SALES_TAX, VAT, GST',
  `rate` decimal(5,2) NOT NULL,
  `name` varchar(100) NOT NULL COMMENT 'Display name: "Central GST", "State Sales Tax", etc.',
  `applicable_from` date DEFAULT NULL COMMENT 'When this rate became effective',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `tax_rules_country_state_tax_type` (`country`,`state`,`tax_type`),
  KEY `tax_rules_country_is_active` (`country`,`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- tenants -----
DROP TABLE IF EXISTS `tenants`;
CREATE TABLE `tenants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `business_name` varchar(255) NOT NULL,
  `slug` varchar(100) NOT NULL COMMENT 'URL-safe unique identifier for the tenant',
  `owner_name` varchar(255) NOT NULL,
  `owner_email` varchar(255) NOT NULL,
  `owner_phone` varchar(20) DEFAULT NULL,
  `country` varchar(2) NOT NULL DEFAULT 'IN' COMMENT 'ISO 3166-1 alpha-2 country code (IN, US, GB, AE)',
  `currency` varchar(3) NOT NULL DEFAULT 'INR',
  `plan` enum('trial','basic','professional','enterprise') DEFAULT 'trial',
  `max_users` int DEFAULT '3' COMMENT 'Max users allowed under this plan',
  `max_companies` int DEFAULT '1' COMMENT 'Max companies allowed under this plan',
  `status` enum('active','suspended','cancelled','trial') DEFAULT 'trial',
  `trial_ends_at` datetime DEFAULT NULL,
  `subscription_ends_at` datetime DEFAULT NULL,
  `address` text,
  `gst_number` varchar(50) DEFAULT NULL COMMENT 'Tax ID of the tenant business',
  `notes` text COMMENT 'Internal notes by super admin',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  UNIQUE KEY `slug_2` (`slug`),
  UNIQUE KEY `slug_3` (`slug`),
  UNIQUE KEY `slug_4` (`slug`),
  UNIQUE KEY `slug_5` (`slug`),
  UNIQUE KEY `slug_6` (`slug`),
  UNIQUE KEY `slug_7` (`slug`),
  UNIQUE KEY `slug_8` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- transactions -----
DROP TABLE IF EXISTS `transactions`;
CREATE TABLE `transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `account_id` int NOT NULL,
  `type` enum('DEBIT','CREDIT') NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `reference_type` varchar(30) NOT NULL COMMENT 'sale, purchase, payment, supplier_payment, manual',
  `reference_id` int DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `transactions_account_id` (`account_id`),
  KEY `transactions_reference_type_reference_id` (`reference_type`,`reference_id`),
  KEY `transactions_created_at` (`created_at`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `transactions_ibfk_15` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `transactions_ibfk_16` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- user_companies -----
DROP TABLE IF EXISTS `user_companies`;
CREATE TABLE `user_companies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `company_id` int NOT NULL,
  `role_id` int NOT NULL COMMENT 'Role within this company',
  `status` enum('active','invited','removed') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_companies_company_id_user_id_unique` (`user_id`,`company_id`),
  UNIQUE KEY `user_companies_user_id_company_id` (`user_id`,`company_id`),
  KEY `user_companies_company_id` (`company_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `user_companies_ibfk_22` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_companies_ibfk_23` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_companies_ibfk_24` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- users -----
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `role_id` int NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `is_super_admin` tinyint(1) DEFAULT '0' COMMENT 'Platform-level super admin (SaaS owner)',
  `tenant_id` int DEFAULT NULL COMMENT 'Which tenant this user belongs to (null for super admin)',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `must_change_password` tinyint(1) DEFAULT '0' COMMENT 'Force password change on next login (set after admin reset / invite)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `email_2` (`email`),
  UNIQUE KEY `email_3` (`email`),
  UNIQUE KEY `email_4` (`email`),
  UNIQUE KEY `email_5` (`email`),
  UNIQUE KEY `email_6` (`email`),
  UNIQUE KEY `email_7` (`email`),
  UNIQUE KEY `email_8` (`email`),
  KEY `role_id` (`role_id`),
  KEY `tenant_id` (`tenant_id`),
  CONSTRAINT `users_ibfk_15` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `users_ibfk_16` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----- warehouses -----
DROP TABLE IF EXISTS `warehouses`;
CREATE TABLE `warehouses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `name_2` (`name`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`),
  UNIQUE KEY `name_5` (`name`),
  UNIQUE KEY `name_6` (`name`),
  UNIQUE KEY `name_7` (`name`),
  UNIQUE KEY `name_8` (`name`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `warehouses_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
